services:
  ccagent-token-rotator-test:
    image: preslavmihaylov/ccagent-token-rotator:latest
    container_name: ccagent-token-rotator-test
    volumes:
      - ./cc.pem:/secrets/cc.pem:ro
      - ./volumes/ccagent-test:/shared:Z
    environment:
      - GITHUB_APP_ID=123456
      - GITHUB_INSTALLATION_ID=123456
    healthcheck:
      test: ["CMD", "test", "-f", "/shared/.config/ccagent/.env"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s
    restart: unless-stopped

  ccagent-test:
    image: preslavmihaylov/ccagent-docker:latest
    container_name: ccagent-test
    depends_on:
      ccagent-token-rotator-test:
        condition: service_healthy
    volumes:
      - ./volumes/ccagent-test:/home/ccagent
    environment:
      - REPO_URL=github.com/presmihaylov/claudecontrol
      - CCAGENT_API_KEY=sys_xyz
      - CLAUDE_CODE_OAUTH_TOKEN=sk-ant-xyz
    working_dir: /workspace
    stdin_open: true
    tty: true
    restart: unless-stopped
