run:
  timeout: 5m
  go: "1.24"

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  govet:
    enable:
      - shadow
  misspell:
    locale: US

linters:
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - errcheck
    - gochecknoinits
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unused
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - mnd
        - gocritic
        - gosec
        - noctx
        - dupl
        - goconst
        - errcheck
    - text: "Magic number"
      linters:
        - mnd
    - text: "duplicate of"
      linters:
        - dupl
    - text: "has .* occurrences, make it a constant"
      linters:
        - goconst
    - text: "Subprocess launched with a potential tainted input"
      linters:
        - gosec
    - text: "response body must be closed"
      linters:
        - bodyclose
    - text: "don't use `init` function"
      linters:
        - gochecknoinits
    - text: "shadow: declaration of"
      linters:
        - govet
    - text: "should not use underscores in Go names"
      linters:
        - stylecheck
  max-issues-per-linter: 0
  max-same-issues: 0
