run:
  timeout: 5m
  go: "1.21"

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(ccbackend)
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  govet:
    enable:
      - shadow
  misspell:
    locale: US
  lll:
    line-length: 140

linters:
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - errcheck
    - gci
    - gochecknoinits
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unused
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - mnd
        - gocritic
        - gosec
        - lll
        - noctx
        - dupl
        - goconst
        - errcheck
    - text: "Magic number"
      linters:
        - mnd
    - text: "duplicate of"
      linters:
        - dupl
    - text: "exceeds the maximum"
      linters:
        - lll
    - text: "has .* occurrences, make it a constant"
      linters:
        - goconst
    - text: "Subprocess launched with a potential tainted input"
      linters:
        - gosec
    - text: "response body must be closed"
      linters:
        - bodyclose
    - text: "don't use `init` function"
      linters:
        - gochecknoinits
    - text: "shadow: declaration of"
      linters:
        - govet
  max-issues-per-linter: 0
  max-same-issues: 0