run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck      # Check for unchecked errors
    - gofmt         # Check whether code was gofmt-ed
    - goimports     # Check import ordering and formatting
    - gosimple      # Simplify code
    - govet         # Examine Go source code and reports suspicious constructs
    - ineffassign   # Detect ineffectual assignments
    - misspell      # Find commonly misspelled English words
    - staticcheck   # Go static analysis
    - typecheck     # Parse and type-check Go code
    - unused        # Check for unused constants, variables, functions and types
    - revive        # Fast, configurable, extensible, flexible, and beautiful linter for Go
    - gosec         # Security-focused linter
    - unconvert     # Remove unnecessary type conversions
    - unparam       # Report unused function parameters
    - copyloopvar   # Check for pointers to enclosing loop variables (replaces exportloopref)
    - nolintlint    # Reports ill-formed or insufficient nolint directives

linters-settings:
  revive:
    rules:
      - name: exported
        disabled: true  # Disable exported comment requirements for existing code
      - name: package-comments
        disabled: true
      - name: var-naming
        arguments: [["ID"], ["VM"]]
        severity: error
        exclude: ["TESTS_.*"]  # Exclude test methods with TESTS_ prefix

  gosec:
    excludes:
      - G104 # Audit errors not checked - we handle this with errcheck
      - G112 # Potential slowloris attack - we set ReadHeaderTimeout

  goimports:
    local-prefixes: github.com/your-org/cc2

issues:
  exclude-use-default: false
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gosec
        - unparam
        - revive
        - errcheck
    # Exclude linting of auto-generated files
    - path: ".*\\.pb\\.go"
      linters:
        - all
    # Exclude exported comment requirements for handlers and models
    - path: "(handlers|models)/"
      linters:
        - revive
      text: "exported.*should have comment"
    # Exclude var-naming for test methods with TESTS_ prefix
    - text: "TESTS_.*should be.*"
      linters:
        - revive
  max-issues-per-linter: 0
  max-same-issues: 0