name: Deploy to Render and Run Migrations

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy-and-migrate:
    runs-on: ubuntu-latest
    
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.PRODUCTION_DB_PASSWORD }}
      SUPABASE_PROJECT_ID: ${{ secrets.PRODUCTION_PROJECT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Render
        uses: JorgeLNJunior/render-deploy@v1.4.5
        id: render-deploy
        with:
          service_id: ${{ secrets.RENDER_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          wait_deploy: true

      - name: Setup Supabase CLI
        if: success()
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Link to Supabase project
        if: success()
        run: supabase link --project-ref $SUPABASE_PROJECT_ID
        working-directory: ./ccbackend

      - name: Deploy migrations to production
        if: success()
        run: supabase db push
        working-directory: ./ccbackend