name: Lint

on:
  push:
    branches: [ main ]
    paths:
      - 'ccbackend/**'
      - 'ccagent/**'
      - '.github/workflows/lint.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'ccbackend/**'
      - 'ccagent/**'
      - '.github/workflows/lint.yml'

jobs:
  lint-ccbackend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
    
    - name: Install golines
      run: go install github.com/segmentio/golines@latest
    
    - name: Install golangci-lint
      run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
        
    - name: Run lint
      run: |
        cd ccbackend
        make lint

  lint-ccagent:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
    
    - name: Install golines and goimports
      run: |
        go install github.com/segmentio/golines@latest
        go install golang.org/x/tools/cmd/goimports@latest
    
    - name: Install golangci-lint
      run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
        
    - name: Run lint
      run: |
        cd ccagent
        make lint