name: Lint

on:
  push:
    branches: [ main ]
    paths:
      - 'ccbackend/**'
      - 'ccagent/**'
      - '.github/workflows/lint.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'ccbackend/**'
      - 'ccagent/**'
      - '.github/workflows/lint.yml'

jobs:
  lint-ccbackend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
        
    - name: Install golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: latest
        working-directory: ccbackend
        args: --timeout=5m

  lint-ccagent:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
        
    - name: Install golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: latest
        working-directory: ccagent
        args: --timeout=5m