name: Validate Supabase Migrations

on:
  pull_request:
    paths:
      - 'ccbackend/supabase/migrations/**'
  workflow_dispatch:

jobs:
  validate-migrations:
    runs-on: ubuntu-latest
    
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.PRODUCTION_DB_PASSWORD }}
      SUPABASE_PROJECT_ID: ${{ secrets.PRODUCTION_PROJECT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Link to Supabase production project
        run: supabase link --project-ref $SUPABASE_PROJECT_ID
        working-directory: ./ccbackend

      - name: Validate migrations (dry run)
        run: supabase db push --dry-run
        working-directory: ./ccbackend

      - name: Check migration diff
        run: supabase db diff --use-migra
        working-directory: ./ccbackend